

<div id="countrydivcontainer" style="border:0px solid gray; width:100%; margin-bottom: 1em; padding: 10px">

<h3 style="background:#FE4641; padding:8px; color:#ffffff;">Frequently Asked Questions</h3>



      <h4>What is subject to ethics review?</h4>
    
  
  
    
      <p style="font-size:14px;">All research with human subjects should obtain ethics  approval from a research ethics committee prior to its initiation. To meet the  definition of research with human subjects, the proposal must constitute  research and it must obtain information from human subjects. Research is  defined as any social science, biomedical, behavioral, or epidemiological  activity that entails systematic collection or analysis of data, with the  intent to develop generalizable knowledge. Human subjects are defined as human  beings (i) who become individually identifiable through investigators  collection, preparation, or use of biological material or medical or other  records, or (ii) who are exposed to manipulation, intervention, observation, or  other interaction with investigators either directly or through alteration of  their environment. Research with human subjects includes studies that use  tissues, samples, data or records from humans, as well as studies that involve  the conduction of interviews, focus groups or surveys, or the observation of  private behavior.</p>
      <p style="font-size:14px;">Activities that do not constitute research with human  subjects are exempted from ethics review. These are activities that do not aim  at the production of generalizable knowledge or do not involve human subjects  in the ways described above. For example, the following activities do not  constitute research with human subjects and are thus exempted from ethics  review:</p>
  <ul style="padding-left:20px; font-size:14px;">
        <li>Studies using data that are publicly available or  generated by observation of public behavior.</li>

        <li>Studies using data, samples, or tissue that already exist  (i.e. the data, samples or tissue have been obtained by others) and are  received by the research team in such a manner that the identity of the  individuals cannot be established.</li>

        <li>Public health activities conducted under recognized public  health authority with the intent to prevent or control of disease or injury,  including surveillance activities aimed only at the identification or control  of a health problem. These are activities that seek the benefit of the  participants or the participants communities, and do not intend to generate  knowledge that is applicable to other populations.</li>
  
        <li>Quality assurance activities or program evaluations aimed  at improving the program at stake, and with no intent to produce generalizable  knowledge.</li>
      </ul>
      <p style="font-size:14px;">Projects might involve multiple components, some of which  might constitute research with human subjects while other components might not.  The components that constitute research with human subjects should undergo  ethics review. Determinations about whether a proposal is exempted from ethics  review should be made by an independent party such as an ethics review  committee.</p>
    
  


  
    
      <h4>What are the international ethical guidelines for research with human subjects?</h4>
    
  
  
    
      <ul style="padding-left:20px; font-size:14px;">
        <li>Declaration of Helsinki of the World Medical Association  (2013 revision): <a href="http://www.wma.net/en/30publications/10policies/b3/" rel="nofollow" >http://www.wma.net/en/30publications/10policies/b3/</a></li>

        <li>International Ethical Guidelines for Biomedical Research  Involving Human Subjects of the Council for International Organizations of  Medical Sciences (CIOMS): <a href="http://www.cioms.ch/publications/guidelines/guidelines_nov_2002_blurb.htm" rel="nofollow" >http://www.cioms.ch/publications/guidelines/guidelines_nov_2002_blurb.htm</a></li>

        <li>International Guidelines for Ethical Review of  Epidemiological Studies of the Council for International Organizations of  Medical Sciences (CIOMS): <a href="http://www.cioms.ch/publications/guidelines/1991_texts_of_guidelines.htm" rel="nofollow" >http://www.cioms.ch/publications/guidelines/1991_texts_of_guidelines.htm</a></li>
      </ul>
    
  


  
    
      <h4>What are the standards of each country for research with human subjects?</h4>
    
  
  
    
      <ul style="padding-left:20px; font-size:14px;">
        <li>International  Compilation of Human Research Standards (2015 edition): <a href="http://www.hhs.gov/ohrp/international/index.html" rel="nofollow" >http://www.hhs.gov/ohrp/international/index.html</a></li>
      </ul>
    
  


  
    
      <h4>How should ethics review committees function?</h4>
    
  
  
    
      <ul style="padding-left:20px; font-size:14px;">
        <li>Standards  and Operational Guidance for Ethics Review of Health-Related Research with  Human Participants published by WHO: <a href="http://whqlibdoc.who.int/publications/2011/9789241502948_eng.pdf?ua=1" rel="nofollow" >http://whqlibdoc.who.int/publications/2011/9789241502948_eng.pdf?ua=1</a></li>
      </ul>
    
  


  
    
      <h4>Which questions should guide the ethics review of research with human subjects?</h4>
    
  
  
    
      <ul style="padding-left:20px; font-size:14px;">
        <li>Social value: Can the study lead to improvements in health  or well-being? What is the potential value of the research for each of the  prospective beneficiaries?</li>
        <li>Scientific validity: Is the investigation methodologically  valid and scientifically (and statistically) sound? Will the study generate  valid and reliable data that can be generalizable? Is the study feasible? Does  the study design ensure participants the health-care interventions they are  entitled to? If not, are there methodologically compelling reasons and are  participants protected from serious harm?</li>

        <li>Fair participant selection: What are the criteria to include  and exclude participants? Is selection of participants based on scientific  criteria? Are research participants selected to minimize risks and maximize  potential benefits? If participants are vulnerable, are there any safeguards to  protect them? Are the risks and potential benefits of the study fairly  distributed?</li>
        <li>Favorable risk-benefit ratio: Can the risks for participants  be minimized? Can potential benefits for individuals and society be improved?  Do the potential benefits for society and individuals outweigh the risks?</li>
        <li>Informed consent: Is the information provided to potential  participants accurate, clear, relevant and complete? Are the recruitment  procedures, consent process and incentives appropriate for their culture and  context? Is there an appropriate plan for obtaining permission for those that  cant consent for themselves? Are the participants being made aware of their  right to refuse to participate and are they actually free to refuse?</li>
      </ul>
      <ul>
        <li>Respect for participants: How will the health and well-being  of participants be monitored to minimize harms? How will their privacy be  protected? Can participants withdraw from the study without penalty? What are  the plans of care after the study is completed? Will participants be given any  new information (including the results of the study)?</li>
      </ul>
      <p style="font-size:14px;">(Adapted from (1) Emanuel E, Wendler D, Grady C. An ethical  framework for biomedical research. In: Emanuel E et al. eds. The Oxford  textbook of clinical research ethics. New York, NY: Oxford University Press;  2008: 123-135. (2) Emanuel E, Wendler D, Grady C. What makes clinical research  ethical? JAMA 2000;283:2701-27711. (3) Emanuel E, Wendler D, Killen J, Grady C.  What makes clinical research in developing countries ethical? The benchmarks of  ethical research. JID 2004;189:930-937.)</p>
    
  










</div>